// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgiMCX1WMKLoiRvAOg8qcZeFwRIkxkkg',
    appId: '1:1024004650566:web:2272da3a1001e6f526fc47',
    messagingSenderId: '1024004650566',
    projectId: 'gentledoseapp',
    authDomain: 'gentledoseapp.firebaseapp.com',
    storageBucket: 'gentledoseapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6k6_xlGSqH5wI6HrK9HJ5bPYchyoBz8',
    appId: '1:1024004650566:android:264b59fa8c13575526fc47',
    messagingSenderId: '1024004650566',
    projectId: 'gentledoseapp',
    storageBucket: 'gentledoseapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5lJ1zIvppRPEk6SDtxbb5Vyk4_q2umWU',
    appId: '1:1024004650566:ios:d6373de7bebfccac26fc47',
    messagingSenderId: '1024004650566',
    projectId: 'gentledoseapp',
    storageBucket: 'gentledoseapp.firebasestorage.app',
    iosBundleId: 'com.example.gentleDose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5lJ1zIvppRPEk6SDtxbb5Vyk4_q2umWU',
    appId: '1:1024004650566:ios:d6373de7bebfccac26fc47',
    messagingSenderId: '1024004650566',
    projectId: 'gentledoseapp',
    storageBucket: 'gentledoseapp.firebasestorage.app',
    iosBundleId: 'com.example.gentleDose',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTgiMCX1WMKLoiRvAOg8qcZeFwRIkxkkg',
    appId: '1:1024004650566:web:ffe692a49d761b4226fc47',
    messagingSenderId: '1024004650566',
    projectId: 'gentledoseapp',
    authDomain: 'gentledoseapp.firebaseapp.com',
    storageBucket: 'gentledoseapp.firebasestorage.app',
  );

}